feat: JWT 토큰 서버 구축
FISOLUTION/fingerprint-backend pull request #11
Opened 2023-07-25 07:54 UTC by ChooSeoyeon

## 🌱 관련 이슈
- close #5 

## 📌 작업 내용
- security, JWT 설정 추가
- Authorization, Authentication 필터 추가
- JWT 토큰 서버 테스트용 API
    - 회원 정보 조회 API
    - 로컬 로그인 API
    - 로컬 회원가입 API

## 📚 기타
- 아직 미완성입니다. 변경 사항 한 눈에 보고 싶어서 먼저 올립니다,, 다 되면 말씀 드릴게요!

2023-07-26 02:54 UTC, uwoobeat requested changes
리뷰 확인 부탁드립니다~

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/auth/service/AuthService.java
> +        if(user == null) {
공백 추가 필요

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/auth/controller/AuthController.java
> +        AuthLoginResponse response =authService.login(request);
공백 필요

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/user/dto/CenterDto.java
> +    public static CenterDto from(Center center) {
변환 로직은 Mapper 클래스에서 처리하기로 하지 않았나요?

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/user/dto/UserDto.java
> +    public static UserDto from(User user) {
마찬가지로 Mapper 클래스에 `from` -> `toXXX`로 변경해주시면 좋을듯 합니다

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/user/service/UserService.java
> +    private final UserMapper userMapper;
매퍼 클래스는 빈이 아니기 때문에 주입하지 않고 `UserMapper:toXXX`와 같이 사용하는 것이 좋을 것 같습니다~

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/global/config/WebSecurityConfig.java
> +                .csrf((csrf) -> csrf.disable()) // csrf 보안 토큰 사용 x
람다식 인자에는 괄호 없어도 될 것 같아요. 가령 `.csrf(csrf -> csrf.disable())` 같이요

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/user/mapper/UserMapper.java
> +@Component
Mapper는 컴포넌트로 등록할 필요 없을 것 같아요

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/user/mapper/UserMapper.java
> +    public UserFindOneResponse toUserFindOneResponse(User user) {
static 붙여주시면 좋을듯

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/teacher/domain/Teacher.java
> +                .userRole(UserRole.TEACHER)
MANAGER일 수도 있지 않나요?
그냥 역할은 열어두는 게 좋을 것 같습니다

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/teacher/domain/Teacher.java
> +    public static Teacher createTeacher(Profile profile, AuthInfo authInfo,  Center center) {
파라미터 간 공백 수정 필요

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/teacher/repository/TeacherRepository.java
> +public interface TeacherRepository extends JpaRepository<Teacher, Long> {
`@Repository` 어노테이션 붙여주셔야 합니다!

2023-07-26 02:54 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/user/service/UserService.java
> +@Transactional
조회 기능은 `@Transactional(readOnly = true)` 옵션 붙여주세요

2023-07-26 02:57 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/teacher/domain/Teacher.java
> +                .userRole(UserRole.TEACHER)
테스트용으로만 쓸 거라서 그냥 TEACHER로 해두었습니다! 테스트용이란 주석이 없었네여 주석 추가할게요!

2023-07-26 03:01 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/teacher/repository/TeacherRepository.java
> +public interface TeacherRepository extends JpaRepository<Teacher, Long> {
붙일 필요 없다로 결정

2023-07-26 03:02 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/teacher/repository/TeacherRepository.java
> +public interface TeacherRepository extends JpaRepository<Teacher, Long> {
++ Spring Data JPA 사용 시 해당 어노테이션을 붙이지 않아도 된다고 합니다

[(레퍼런스)](https://velog.io/@dltkdgns3435/SpringBoot-spring-data-jpa-%EC%82%AC%EC%9A%A9%EC%8B%9C-Repository-%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98%EC%9D%80-%EA%BC%AD-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80#-repository%EC%99%80-spring-data-jpa)

2023-07-26 03:06 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/global/config/WebSecurityConfig.java
> +                .csrf((csrf) -> csrf.disable()) // csrf 보안 토큰 사용 x
넣기로 결정

2023-07-26 03:13 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/user/service/UserService.java
> +    private final UserMapper userMapper;
BCryptPasswordEncoder 때문에 TODO로 보류

2023-07-26 03:13 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/user/mapper/UserMapper.java
> +@Component
BCryptPasswordEncoder 때문에 TODO로 보류

2023-07-26 03:13 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/user/mapper/UserMapper.java
> +    public UserFindOneResponse toUserFindOneResponse(User user) {
BCryptPasswordEncoder 때문에 TODO로 보류

2023-07-26 03:18 UTC, uwoobeat approved these changes
todo 추가하신 것 맞나요?
그리고 커밋메세지 대문자 불편해요
일단 어푸루부드림

2023-07-26 03:32 UTC, merged

2023-08-04 06:27 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/user/service/UserService.java
> +    private final UserMapper userMapper;
component 방식으로 변경됨!

2023-08-04 06:27 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/user/mapper/UserMapper.java
> +@Component
컴포넌트 방식으로 변경됨!