feat: 방문일정 상세 조회 작성자 검증 로직 추가
FISOLUTION/fingerprint-backend pull request #67
Opened 2023-08-08 06:54 UTC by ChooSeoyeon

## 🌱 관련 이슈
- close #54

## 📌 작업 내용
- 방문일정 상세 조회 시 본인 센터의 방문일정만 조회 가능하게 검증하는 로직을 추가했습니다.

## 📚 기타
- Application.java와 Schedule.java의  isPublishedBy 함수의 이름을  isCreatedBy로 바꾸는 거 어떻게 생각하시나요? 일단은 기존 컨벤션(Application)에 맞춰 저도 isPublishedBy로 이름 지어줬습니다.

2023-08-09 02:44 UTC, uwoobeat commented
@ChooSeoyeon 

CRUD 워딩 -> 실행주체가 서비스 애플리케이션
그 외 워딩 -> 실행주체가 도메인 객체
(ex: Publish - Create, Unregister - Delete)

도메인에는 그 도메인 컨텍스트에 특화된 언어를 사용하는 것이 좋다고 생각합니다 (참고: [도메인 주도 개발 - 보편언어](https://incheol-jung.gitbook.io/docs/q-and-a/architecture/ddd#undefined-1))

신청서의 경우 신청자를 기준으로 신청서를 등록한 사람이 있고, 신청서를 기준으로 신청서를 발행(publish)한 사람이 있으므로 `isPublishedBy`가 적절한 표현일 것 같습니다. 발행이 아닌 생성(create)를 사용하게 되는 경우 신청서 생성, 신청서 생성자 같은 워딩을 사용하게 되는데, 이는 맥락이 잘 드러나지 않기 때문에 좋지 않다고 판단했습니다.

2023-08-09 04:23 UTC, uwoobeat requested changes

2023-08-09 04:23 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/schedule/service/ScheduleService.java
> +    private void validateScheduleOwnership(Schedule schedule, Center center) {
이 메서드는 방문일정과 센터를 받아서 방문일정을 발행한 센터가 인자로 받은 센터가 맞는지 비교합니다.
그리고 방문일정을 발행한 센터가 인자로 받은 센터가 아니면 `FORBIDDEN_USER` 예외를 발생시킵니다.
메서드 이름은 '방문일정의 소유권을 검증한다'는 의미를 가집니다.

만약에 신입이 들어와서 코드를 본다고 칩시다. 방문일정을 발행한 센터와 인자로 받은 센터가 일치하지 않는다면, 센터는 그 방문일정에 대한 소유권을 가지고 있지 않기 때문에 예외를 발생시킨다고 추측할 수 있습니다. 이 정도는 누구나 생각할 수 있으니까요.

근데 센터가 소유권을 가지고 있지 않는 상황이고, 이 메서드도 센터의 소유권을 검증하는데 왜 유저의 접근권한이 없다는 'FORBIDDEN_USER' 예외가 발생할까요? `FORBIDDEN_CENTER`가 발생하는 것이 이치에 맞지 않나요?

결국 1) 유저 로직 중 일부가 컨트롤러에서 구현되며 2) 메서드 이름이 명료하지 않아 이런 문제가 발생합니다.
이 부분만 위에서 언급한 내용 참고하여 수정하시면 될 것 같습니다.

2023-08-09 05:27 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/schedule/domain/Schedule.java
> +    public boolean isPublishedBy(Center center) {
메서드 이름 isOwnedBy 어떨까요

2023-08-09 08:05 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/schedule/service/ScheduleService.java
> +    private void validateScheduleOwnership(Schedule schedule, Center center) {
현재 userUtils 적용이 안된 상태라 controller에서 principalDetails로 가져온 teacher를 가져다 썼습니다. 같이 올라와있던 userUtils 관련 pr이 이제 머지되었으니 적용하겠습니다.

2023-08-09 08:25 UTC, uwoobeat requested changes

2023-08-09 08:25 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/schedule/domain/Schedule.java
> +    public boolean isOwnedBy(Long centerId) {
center로 비교하면 안되나요? 굳이 centerId로 비교하는 이유가 있나요?

2023-08-09 08:25 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/schedule/service/ScheduleService.java
> +            throw new CustomException(ErrorCode.FORBIDDEN_USER);
아까 전에 남겼던 리뷰 다시 인용합니다.

> 이 메서드는 방문일정과 센터를 받아서 방문일정을 발행한 센터가 인자로 받은 센터가 맞는지 비교합니다.
그리고 방문일정을 발행한 센터가 인자로 받은 센터가 아니면 `FORBIDDEN_USER` 예외를 발생시킵니다.
메서드 이름은 '방문일정의 소유권을 검증한다'는 의미를 가집니다.

> 만약에 신입이 들어와서 코드를 본다고 칩시다. 방문일정을 발행한 센터와 인자로 받은 센터가 일치하지 않는다면, 센터는 그 방문일정에 대한 소유권을 가지고 있지 않기 때문에 예외를 발생시킨다고 추측할 수 있습니다. 이 정도는 누구나 생각할 수 있으니까요.

> 근데 센터가 소유권을 가지고 있지 않는 상황이고, 이 메서드도 센터의 소유권을 검증하는데 왜 유저의 접근권한이 없다는 'FORBIDDEN_USER' 예외가 발생할까요? `FORBIDDEN_CENTER`가 발생하는 것이 이치에 맞지 않나요?

2023-08-09 08:34 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/schedule/domain/Schedule.java
> +    public boolean isOwnedBy(Long centerId) {
도메인 객체는 `matchesId`를 호출해서 id의 일치여부를 비교하는 것보다,
`equals()`의 로직을 결정하는 `hashcode()`를 오버라이딩해서 `equals()`로 비교하는 쪽이 더 캡슐화를 잘 지킬 수 있습니다.

가령 validation 로직에서도 두 JPA 엔티티를 비교해야 한다고 했을 때,
`teacherToBeCompared.equals(teacherToCompare)`과
`teaacherToBeCompared.matchesId(TeacherToCompare.getId())`중
후자의 경우 `TeacherToCompare`의 id값을 직접 노출시켜서 비교하고 있기 때문에 디미터 법칙이 잘 지켜지지 않게 됩니다.

jpa entity의 hashcode 오버라이딩은 [이 링크](https://velog.io/@park2348190/JPA-Entity%EC%9D%98-equals%EC%99%80-hashCode)를 참고하시면 좋을 듯합니다.

2023-08-09 09:14 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/schedule/domain/Schedule.java
> +    public boolean isOwnedBy(Long centerId) {
equals가 proxy 문제로 사용 안하고 있었는데 hashcode() 쓰면 문제 없겠네용! 적용해보겠습니다!

2023-08-09 09:15 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/schedule/service/ScheduleService.java
> +            throw new CustomException(ErrorCode.FORBIDDEN_USER);
이 함수까지는 teacher를 넘겨주는 방식이 낫겠네요!

2023-08-09 09:16 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/schedule/controller/ScheduleController.java
> +        ScheduleFindOneResponse response = scheduleService.findOneSchedule(scheduleId, center);
마찬가지로 userUtils가 해당 pr에 적용이 안되어 일시적으로 발생한 문제였습니다. 현재는 userUtils 반영해서 수정되었습니다!

2023-08-10 06:04 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/center/domain/Center.java
> +    public boolean equals(Object obj) {
이 메서드만 설명해주실 수 있나요?

2023-08-10 06:13 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/center/domain/Center.java
> +    public boolean equals(Object obj) {
프록시 객체도 비교해주기 위해 equals()를 오버라이딩해줬습니다. 
관련 레퍼런스는 아래와 같습니다.
https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/
https://velog.io/@park2348190/JPA-Entity%EC%9D%98-equals%EC%99%80-hashCode

2023-08-10 06:41 UTC, uwoobeat approved these changes

2023-08-10 06:41 UTC, uwoobeat commented on src/main/java/app/iluvit/fingerprint/domain/center/domain/Center.java
> +    public boolean equals(Object obj) {
확인했습니다. 사실은 왜 `Hibernate.getClass`를 썼는지 궁금했는데 찾아보니 프록시가 아닌 실체 구현체를 보기 위함이네요.
별개로 Tecoble에서 올린 레퍼런스를 보면 `instanceof`를 쓰는 방법도 있다고 합니다. 한번 참고해보시길... ㅎㅎ

https://tecoble.techcourse.co.kr/post/2022-10-17-jpa-hibernate-proxy/

2023-08-10 06:46 UTC, ChooSeoyeon commented on src/main/java/app/iluvit/fingerprint/domain/center/domain/Center.java
> +    public boolean equals(Object obj) {
예시 커밋 보시면 instanceof 쓴 코드도 있습니다! 저도 고민하다가 instanceof 쓰는 게 좀 더 주류인거 같아서 바꿔줬슴다

2023-08-10 06:46 UTC, merged